export const TEXT = {
  zh_hant: {
    login: '登入',
    loginSuccess: '登入成功',
    logout: '登出',
    logoutFailed: '登出失敗，請重試',
    register: '註冊',
    previousStep: '上一步',
    nextStep: '下一步',
    welcomeAuthor: '歡迎成為創作者',
    close: '關閉',
    confirm: '確認',
    email: '電子信箱',
    yourEmail: '你的電子信箱',
    enterEmail: '請輸入電子信箱',
    enterNewEmail: '請輸入新電子信箱',
    enterRegisteredEmail: '請輸入你的註冊電子信箱',
    invalidEmail: '電子信箱格式有誤',
    enterUserName: '請輸入新 Matters ID',
    enterUserNameAgign: '請再次輸入新 Matters ID',
    invalidUserName: 'Matters ID 不一致',
    loginPassword: '登入密碼',
    enterPassword: '請輸入密碼',
    enterPasswordAgain: '請再次輸入密碼',
    forgetPassword: '忘記密碼',
    changePassword: '修改密碼',
    changePasswordSuccess: '密碼修改成功',
    passwordHint: '不少於 8 個字元，必須為英文大小寫字母、數字和特殊符號的組合',
    passwordNotMatch: '密碼不一致',
    userNameHint: '最多輸入至 40 個字元，僅支持英文、數字及 _',
    displayNameHint: '2-20 個字元，仅支持中英文或数字',
    descriptionHint: '建議 50 字以內，最長 200 字',
    hasNoAccount: '沒有帳號',
    verificationCode: '驗證碼',
    sendVerificationCode: '發送驗證碼',
    enterVerificationCode: '請輸入驗證碼',
    resetPassword: '重置密碼',
    resetPasswordSuccess: '密碼重置成功',
    useNewPassword: '請使用新的密碼重新登入',
    required: '必填欄位',
    about: '關於我們',
    guide: '社區约章',
    faq: '常見問題',
    term: '用戶協議',
    termAndPrivacy: '用戶協議與隱私政策',
    termHint: '我們的用戶協議和隱私政策發生了更改，請閱讀並同意後繼續使用。',
    disagree: '我不同意',
    agreeAndContinue: '同意並繼續',
    untitle: '未命名',
    changeEmail: '修改電子信箱',
    changeEmailSuccess: '電子信箱修改成功',
    changeUserName: '修改 Matters ID',
    changeUserNameSuccess: 'Matters ID 修改成功',
    accountFrozen: '帳戶已凍結',
    accountArchived: '帳戶已註銷',
    accountBanned: '帳戶已禁言',
    publish: '發佈作品',
    published: '作品已發佈',
    publishing: '正在發佈',
    waitingForPublish: '正在等待發佈',
    publishFailed: '發失敗',
    publishNote: '發佈須知',
    onboardingInfo: '你還不是創作者',
    articleArchived: '該作品已從站內隱藏',
    commentDeleted: '評論已被刪除',
    back: '返回',
    backToDiscover: '返回發現',
    discover: '發現',
    write: '創作',
    follow: '追蹤',
    following: '追蹤中',
    follower: '追蹤者',
    myFollowees: '我追蹤的',
    followingMe: '追蹤我的',
    followingYou: '追蹤了你',
    mutualFollowing: '互相追蹤',
    unfollow: '取消追蹤',
    followed: '已追蹤',
    followAuthor: '追蹤創作者',
    authorRecommend: '作者推薦',
    allAuthors: '全部作者',
    comment: '評論',
    article: '作品',
    readHistory: '瀏覽記錄',
    myBookmarks: '我的收藏',
    myComments: '我的評論',
    myDrafts: '我的草稿',
    myArticles: '我的作品',
    myWallet: '我的钱包',
    myProfile: '个人页面',
    user: '用戶',
    tag: '標籤',
    allTags: '全部標籤',
    topic: '話題',
    allTopics: '全部話題',
    hotTopics: '熱議話題',
    viewAll: '查看全部',
    reply: '回覆',
    retry: '重試',
    revoke: '撤銷',
    report: '檢舉',
    resend: '重新發送',
    change: '修改',
    edit: '編輯',
    save: '儲存',
    delete: '刪除',
    cancel: '取消',
    done: '完成',
    setting: '設定',
    accountSetting: '帳戶設定',
    notificationSetting: '通知設定',
    uiSetting: '介面設定',
    userProfile: '個人簡介',
    articleFingerprint: '作品指紋',
    copySuccess: '複製成功',
    copy: '複製',
    pin: '置頂',
    cancelPin: '取消置頂',
    emptySearchResults: '没有找到你搜索的内容',
    uploadImageSuccess: '图片上传成功',
    uploadImageFailed: '图片上传失败',
    error: {
      UNKNOWN_ERROR: '未知錯誤，請稍候重試',
      NETWORK_ERROR: '網路錯誤，請稍候重試',
      INTERNAL_SERVER_ERROR: '伺服器錯誤，請稍候重試',
      BAD_USER_INPUT: '輸入有誤',
      UNAUTHENTICATED: '請先登入再進行操作',
      FORBIDDEN: '你尚無權限進行該操作',
      TOKEN_INVALID: '登入信息已失效，請重新登入',
      ENTITY_NOT_FOUND: '實體不存在',
      USER_NOT_FOUND: '用戶不存在',
      COMMENT_NOT_FOUND: '評論不存在',
      ARTICLE_NOT_FOUND: '作品不存在',
      ASSET_NOT_FOUND: '資源不存在',
      DRAFT_NOT_FOUND: '草稿不存在',
      TAG_NOT_FOUND: '標籤不存在',
      NOTICE_NOT_FOUND: '通知不存在',
      NOT_ENOUGH_MAT: '沒有足夠的 MAT 以讚賞',
      USER_EMAIL_INVALID: '電子信箱不正確',
      USER_EMAIL_EXISTS: '該電子信箱已被其他使用者使用',
      USER_EMAIL_NOT_FOUND: '帳號不正確',
      USER_PASSWORD_INVALID: '密碼不正確',
      USER_USERNAME_INVALID: 'Matters ID 不正確',
      USER_USERNAME_EXISTS: '該 Matters ID 已被其他使用者使用',
      USER_DISPLAYNAME_INVALID: '姓名不正確',
      USER_FOLLOW_FAILED: '追蹤用戶失敗，請稍候重試',
      // USER_INVITE_FAILED: '',
      // USER_INVITE_STATE_INVALID: '',
      // USER_INVITE_EMAIL_REGISTERED: '',
      // USER_INVITE_EMAIL_INVITED: '',
      CODE_INVALID: '驗證碼不正確',
      CODE_EXPIRED: '驗證碼已過期'
    } as { [key: string]: string }
  },

  zh_hans: {
    login: '登入',
    loginSuccess: '登入成功',
    logout: '登出',
    logoutFailed: '登出失败，请重试',
    register: '注册',
    welcomeAuthor: '欢迎成为创作者',
    previousStep: '上一步',
    nextStep: '下一步',
    close: '关闭',
    confirm: '确认',
    email: '邮箱',
    yourEmail: '你的邮箱',
    enterEmail: '请输入邮箱',
    enterNewEmail: '请输入新邮箱',
    enterRegisteredEmail: '请输入你的注册邮箱',
    invalidEmail: '邮箱格式有误',
    enterUserName: '请输入新 Matters ID',
    enterUserNameAgign: '请再次输入新 Matters ID',
    invalidUserName: 'Matters ID 不一致',
    loginPassword: '登入密码',
    enterPassword: '请输入密码',
    enterPasswordAgain: '请再次输入密码',
    forgetPassword: '忘记密码',
    changePassword: '修改密码',
    changePasswordSuccess: '密碼修改成功',
    passwordHint: '不少于 8 个字符，必须为英文大小写字母、数字和特殊符号的组合',
    userNameHint: '最多输入至 40 个字符，仅支持英文、数字及 _',
    displayNameHint: '2-20 个字符，仅支持中英文或数字',
    descriptionHint: '建议 50 字以内，最长 200 字',
    passwordNotMatch: '密码不一致',
    hasNoAccount: '没有帐号',
    verificationCode: '驗證碼',
    sendVerificationCode: '发送验证码',
    enterVerificationCode: '请输入验证码',
    resetPassword: '重置密码',
    resetPasswordSuccess: '密码重置成功',
    useNewPassword: '请使用新的密码重新登入',
    required: '必填栏位',
    about: '关于我们',
    guide: '社区约章',
    faq: '常见问题',
    term: '用户协议',
    termAndPrivacy: '用户协议与隐私政策',
    termHint: '我们的用户协议和隐私政策发生了更改，请阅读并同意后继续使用。',
    disagree: '我不同意',
    agreeAndContinue: '同意并继续',
    untitle: '未命名',
    changeEmail: '修改邮箱',
    changeEmailSuccess: '邮箱修改成功',
    changeUserName: '修改 Matters ID',
    changeUserNameSuccess: 'Matters ID 修改成功',
    accountFrozen: '账户已冻结',
    accountArchived: '账户已注销',
    accountBanned: '账户已禁言',
    publish: '发布作品',
    published: '作品已发布',
    publishing: '正在发布',
    waitingForPublish: '正在等待发布',
    publishNote: '发布须知',
    publishFailed: '发布失败',
    onboardingInfo: '你还不是创作者',
    articleArchived: '该作品已从站内隐藏',
    commentDeleted: '评论已被删除',
    back: '返回',
    backToDiscover: '返回发现',
    discover: '返回',
    write: '创作',
    follow: '追踪',
    following: '追踪中',
    follower: '追踪者',
    myFollowees: '我追踪的',
    followingMe: '追踪我的',
    followingYou: '追踪了你',
    mutualFollowing: '互相追踪',
    unfollow: '取消追踪',
    followed: '已追踪',
    followAuthor: '追踪创作者',
    authorRecommend: '作者推荐',
    allAuthors: '全部作者',
    comment: '评论',
    article: '作品',
    readHistory: '浏览记录',
    myBookmarks: '我的收藏',
    myComments: '我的评论',
    myDrafts: '我的草稿',
    myArticles: '我的作品',
    myWallet: '我的錢包',
    myProfile: '個人頁面',
    user: '用戶',
    tag: '标签',
    allTags: '全部标签',
    topic: '话题',
    allTopics: '全部话题',
    hotTopics: '热议话题',
    viewAll: '查看全部',
    reply: '回复',
    retry: '重试',
    revoke: '撤销',
    report: '检举',
    resend: '重新发送',
    change: '修改',
    edit: '编辑',
    save: '保存',
    delete: '删除',
    cancel: '取消',
    done: '完成',
    setting: '设定',
    accountSetting: '账户设定',
    notificationSetting: '通知设定',
    uiSetting: '界面设定',
    userProfile: '个人简介',
    articleFingerprint: '作品指纹',
    copySuccess: '复制成功',
    copy: '复制',
    pin: '置顶',
    cancelPin: '取消置顶',
    emptySearchResults: '沒有找到你搜尋的內容',
    uploadImageSuccess: '圖片上傳成功',
    uploadImageFailed: '圖片上傳失敗',
    error: {
      UNKNOWN_ERROR: '未知错误，请稍候重试',
      NETWORK_ERROR: '網路錯誤，请稍候重试',
      INTERNAL_SERVER_ERROR: '服务器错误，请稍候重试',
      BAD_USER_INPUT: '输入有误',
      UNAUTHENTICATED: '请先登入再进行操作',
      FORBIDDEN: '你尚无权限进行该操作',
      TOKEN_INVALID: '登入信息已失效，请重新登入',
      ENTITY_NOT_FOUND: '实体不存在',
      USER_NOT_FOUND: '用户不存在',
      COMMENT_NOT_FOUND: '评论不存在',
      ARTICLE_NOT_FOUND: '作品不存在',
      ASSET_NOT_FOUND: '资源不存在',
      DRAFT_NOT_FOUND: '草稿不存在',
      TAG_NOT_FOUND: '标签不存在',
      NOTICE_NOT_FOUND: '通知不存在',
      NOT_ENOUGH_MAT: '没有足够的 MAT 以赞赏',
      USER_EMAIL_INVALID: '邮箱不正确',
      USER_EMAIL_EXISTS: '该邮箱已被其他用户使用',
      USER_EMAIL_NOT_FOUND: '帐号不正确',
      USER_PASSWORD_INVALID: '密码不正确',
      USER_USERNAME_INVALID: 'Matters ID 不正确',
      USER_USERNAME_EXISTS: '该 Matters ID 已被其他用户使用',
      USER_DISPLAYNAME_INVALID: '姓名不正确',
      USER_FOLLOW_FAILED: '追踪用户失败，请稍候重试',
      // USER_INVITE_FAILED: '',
      // USER_INVITE_STATE_INVALID: '',
      // USER_INVITE_EMAIL_REGISTERED: '',
      // USER_INVITE_EMAIL_INVITED: '',
      CODE_INVALID: '验证码不正确',
      CODE_EXPIRED: '验证码已过期'
    } as { [key: string]: string }
  }
}
