export const TEXT = {
  zh_hant: {
    login: '登入',
    register: '註冊',
    previousStep: '上一步',
    nextStep: '下一步',
    welcomeAuthor: '歡迎成為創作者',
    close: '關閉',
    confirm: '確認',
    enterEmail: '請輸入電子信箱',
    enterRegisteredEmail: '請輸入你的註冊電子信箱',
    invalidEmail: '電子信箱格式有誤',
    enterPassword: '請輸入密碼',
    enterPasswordAgain: '請再次輸入密碼',
    forgetPassword: '忘記密碼',
    passwordHint: '不少於 8 個字元，必須為英文大小寫字母、數字和特殊符號的組合',
    passwordNotMatch: '密碼不一致',
    hasNoAccount: '沒有帳號',
    verificationCode: '驗證碼',
    sendVerificationCode: '發送驗證碼',
    resetPassword: '重置密碼',
    resetPasswordSuccess: '密碼重置成功',
    useNewPassword: '請使用新的密碼重新登入',
    required: '必填欄位',
    term: '用戶協議',
    termAndPrivacy: '用戶協議與隱私政策',
    termHint: '我們的用戶協議和隱私政策發生了更改，請閱讀並同意後繼續使用。',
    disagree: '我不同意',
    agreeAndContinue: '同意並繼續',
    untitle: '未命名',
    changeEmail: '修改電子信箱',
    changeUserName: '修改 Matters ID',
    accountFrozen: '帳戶已凍結',
    accountArchived: '帳戶已註銷',
    accountBanned: '帳戶已禁言',
    publish: '發佈文章',
    publishNote: '發佈須知',
    onboardingInfo: '你還不是創作者',
    error: {
      UNKNOWN_ERROR: '未知錯誤，請稍候重試',
      NETWORK_ERROR: '網路錯誤，請稍候重試',
      INTERNAL_SERVER_ERROR: '伺服器錯誤，請稍候重試',
      BAD_USER_INPUT: '輸入有誤',
      UNAUTHENTICATED: '請先登入再進行操作',
      FORBIDDEN: '你尚無權限進行該操作',
      TOKEN_INVALID: '登入信息已失效，請重新登入',
      ENTITY_NOT_FOUND: '實體不存在',
      USER_NOT_FOUND: '用戶不存在',
      COMMENT_NOT_FOUND: '評論不存在',
      ARTICLE_NOT_FOUND: '文章不存在',
      ASSET_NOT_FOUND: '資源不存在',
      DRAFT_NOT_FOUND: '草稿不存在',
      TAG_NOT_FOUND: '標籤不存在',
      NOTICE_NOT_FOUND: '通知不存在',
      NOT_ENOUGH_MAT: '沒有足夠的 MAT 以讚賞',
      USER_EMAIL_INVALID: '電子信箱不正確',
      USER_EMAIL_EXISTS: '該電子信箱已被其他使用者使用',
      USER_EMAIL_NOT_FOUND: '帳號不正確',
      USER_PASSWORD_INVALID: '密碼不正確',
      USER_USERNAME_INVALID: 'Matters ID 不正確',
      USER_USERNAME_EXISTS: '該 Matters ID 已被其他使用者使用',
      USER_DISPLAYNAME_INVALID: '姓名不正確',
      USER_FOLLOW_FAILED: '追蹤用戶失敗，請稍候重試',
      // USER_INVITE_FAILED: '',
      // USER_INVITE_STATE_INVALID: '',
      // USER_INVITE_EMAIL_REGISTERED: '',
      // USER_INVITE_EMAIL_INVITED: '',
      CODE_INVALID: '驗證碼不正確',
      CODE_EXPIRED: '驗證碼已過期'
    } as { [key: string]: string }
  },

  zh_hans: {
    login: '登入',
    register: '注册',
    welcomeAuthor: '欢迎成为创作者',
    previousStep: '上一步',
    nextStep: '下一步',
    close: '关闭',
    confirm: '确认',
    enterEmail: '请输入邮箱',
    enterRegisteredEmail: '请输入你的注册邮箱',
    invalidEmail: '邮箱格式有误',
    enterPassword: '请输入密码',
    enterPasswordAgain: '请再次输入密码',
    forgetPassword: '忘记密码',
    passwordHint: '不少于 8 个字符，必须为英文大小写字母、数字和特殊符号的组合',
    passwordNotMatch: '密码不一致',
    hasNoAccount: '没有帐号',
    verificationCode: '驗證碼',
    sendVerificationCode: '发送验证码',
    resetPassword: '重置密码',
    resetPasswordSuccess: '密码重置成功',
    useNewPassword: '请使用新的密码重新登入',
    required: '必填栏位',
    term: '用户协议',
    termAndPrivacy: '用户协议与隐私政策',
    termHint: '我们的用户协议和隐私政策发生了更改，请阅读并同意后继续使用。',
    disagree: '我不同意',
    agreeAndContinue: '同意并继续',
    untitle: '未命名',
    changeEmail: '修改邮箱',
    changeUserName: '修改 Matters ID',
    accountFrozen: '账户已冻结',
    accountArchived: '账户已注销',
    accountBanned: '账户已禁言',
    publish: '发布文章',
    publishNote: '发布须知',
    onboardingInfo: '你还不是创作者',
    error: {
      UNKNOWN_ERROR: '未知错误，请稍候重试',
      NETWORK_ERROR: '網路錯誤，请稍候重试',
      INTERNAL_SERVER_ERROR: '服务器错误，请稍候重试',
      BAD_USER_INPUT: '输入有误',
      UNAUTHENTICATED: '请先登入再进行操作',
      FORBIDDEN: '你尚无权限进行该操作',
      TOKEN_INVALID: '登入信息已失效，请重新登入',
      ENTITY_NOT_FOUND: '实体不存在',
      USER_NOT_FOUND: '用户不存在',
      COMMENT_NOT_FOUND: '评论不存在',
      ARTICLE_NOT_FOUND: '文章不存在',
      ASSET_NOT_FOUND: '资源不存在',
      DRAFT_NOT_FOUND: '草稿不存在',
      TAG_NOT_FOUND: '标签不存在',
      NOTICE_NOT_FOUND: '通知不存在',
      NOT_ENOUGH_MAT: '没有足够的 MAT 以赞赏',
      USER_EMAIL_INVALID: '邮箱不正确',
      USER_EMAIL_EXISTS: '该邮箱已被其他用户使用',
      USER_EMAIL_NOT_FOUND: '帐号不正确',
      USER_PASSWORD_INVALID: '密码不正确',
      USER_USERNAME_INVALID: 'Matters ID 不正确',
      USER_USERNAME_EXISTS: '该 Matters ID 已被其他用户使用',
      USER_DISPLAYNAME_INVALID: '姓名不正确',
      USER_FOLLOW_FAILED: '追踪用户失败，请稍候重试',
      // USER_INVITE_FAILED: '',
      // USER_INVITE_STATE_INVALID: '',
      // USER_INVITE_EMAIL_REGISTERED: '',
      // USER_INVITE_EMAIL_INVITED: '',
      CODE_INVALID: '验证码不正确',
      CODE_EXPIRED: '验证码已过期'
    } as { [key: string]: string }
  }
}
