export const TEXT = {
  zh_hant: {
    login: '登入',
    register: '註冊',
    previousStep: '上一步',
    nextStep: '下一步',
    confirm: '確認',
    enterEmail: '請輸入電子信箱',
    enterRegisteredEmail: '請輸入你的註冊電子信箱',
    invalidEmail: '電子信箱格式有誤',
    enterPassword: '請輸入密碼',
    enterPasswordAgain: '請再次輸入密碼',
    forgetPassword: '忘記密碼',
    passwordHint: '不少於8位，必須包含數字和大小寫字母',
    passwordNotMatch: '密碼不一致',
    hasNoAccount: '沒有帳號',
    verificationCode: '驗證碼',
    sendVerificationCode: '發送驗證碼',
    resetPassword: '重置密碼',
    resetPasswordSuccessful: '密碼重置成功',
    useNewPassword: '請使用新的密碼重新登入',
    required: '必填欄位',
    term: '用戶協議',
    termHint: '我們的用戶協議和隱私政策發生了更改，請閱讀並同意後繼續使用。',
    disagree: '我不同意',
    agreeAndContinue: '同意並繼續'
  },

  zh_hans: {
    login: '登入',
    register: '注册',
    previousStep: '上一步',
    nextStep: '下一步',
    confirm: '确认',
    enterEmail: '请输入邮箱',
    enterRegisteredEmail: '请输入你的注册邮箱',
    invalidEmail: '邮箱格式有误',
    enterPassword: '请输入密码',
    enterPasswordAgain: '请再次输入密码',
    forgetPassword: '忘记密码',
    passwordHint: '少于8位，必须包含数字和大小写字母',
    passwordNotMatch: '密码不一致',
    hasNoAccount: '没有帐号',
    verificationCode: '驗證碼',
    sendVerificationCode: '发送验证码',
    resetPassword: '重置密码',
    resetPasswordSuccessful: '密码重置成功',
    useNewPassword: '请使用新的密码重新登入',
    required: '必填栏位',
    term: '用户协议',
    termHint: '我们的用户协议和隐私政策发生了更改，请阅读并同意后继续使用。',
    disagree: '我不同意',
    agreeAndContinue: '同意并继续'
  }
}
