kind: pipeline
name: default

steps:
  - name: node modules
    image: node:10.14
    commands:
      - npm install --no-progress --quiet --unsafe-perm >  npm-install.log

  - name: tslint
    image: node:10.14
    commands:
      - npm run lint
      - npm run format:check

  - name: build
    image: node:10.14
    commands:
      - npm run build

  # === CI tasks for `develop` branch ===
  - name: develop:upload
    image: plugins/s3
    settings:
      bucket: web-develop.matters.news
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      region: ap-southeast-1
      source: build/**/*
      target: /assets
    when:
      branch:
        - develop
        - feature/dotenv
      event:
        - push

  - name: develop:deploy
    image: matters/awsebcli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: ap-southeast-1
    commands:
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set aws_default_region $AWS_DEFAULT_REGION
      - bash ./bin/eb-deploy.sh develop
    when:
      branch:
        - develop
      event:
        - push

  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: log_github
    username: Drone CI - Matters Web
    when:
      status: [success, failure]
