kind: pipeline
name: default

steps:
  - name: node modules
    image: node:12.16
    commands:
      - npm install --no-progress --quiet --unsafe-perm >  npm-install.log

  - name: tslint
    image: node:12.16
    commands:
      - npm run gen:clean
      - npm run gen:type
      - npm run lint
      - npm run format:check

  - name: test
    image: node:12.16
    environment:
      CODECOV_TOKEN: f109cbf6-b6c7-4a08-ad03-981bc4cd1fe8
      MATTERS_ENV: test
      API_URL: http://matters-server-develop.ap-southeast-1.elasticbeanstalk.com/graphql
    commands:
      - npm install codecov -g
      - npm run test
      - codecov

  # === CI tasks for `develop` branch ===
  - name: develop:build
    image: node:12.16
    commands:
      - cp .env.dev .env
      - npm run build
    when:
      branch:
        - develop

  - name: develop:upload
    image: plugins/s3
    settings:
      bucket: web-develop.matters.news
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      region: ap-southeast-1
      source: build/**/*
      target: /_next
      strip_prefix: build/
    when:
      branch:
        - develop
      event:
        - push

  - name: develop:deploy
    image: matters/awsebcli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: ap-southeast-1
    commands:
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set aws_default_region $AWS_DEFAULT_REGION
      - bash ./bin/eb-deploy.sh develop
    when:
      branch:
        - develop
      event:
        - push

  - name: develop:bdd
    image: node:12.16
    failure: ignore
    environment:
      BDD_USER:
        from_secret: BDD_USER
      BDD_PASSWD:
        from_secret: BDD_PASSWD
      BDD_TEST_USER_EMAIL:
        from_secret: BDD_TEST_USER_EMAIL
      BDD_TEST_USER_PASSWD:
        from_secret: BDD_TEST_USER_PASSWD
    commands:
      - sh bdd/shells/init.sh
      - BDD_DRIVER=default npm run bdd
    when:
      branch:
        - develop
      event:
        - push

  # === CI tasks for `master` branch ===
  - name: prod:build
    image: node:12.16
    commands:
      - cp .env.prod .env
      - npm run build
    when:
      branch:
        - master

  - name: prod:upload
    image: plugins/s3
    settings:
      bucket: matters.news
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      region: ap-southeast-1
      source: build/**/*
      target: /_next
      strip_prefix: build/
    when:
      branch:
        - master
      event:
        - push

  - name: prod:deploy
    image: matters/awsebcli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: ap-southeast-1
    commands:
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set aws_default_region $AWS_DEFAULT_REGION
      - bash ./bin/eb-deploy.sh prod
    when:
      branch:
        - master
      event:
        - push

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK_URL
      channel: log_github
    username: Drone CI - Matters Web
    when:
      status: [success, failure]
