/**
 * `<Icon>` component that render as `<svg>`
 *
 * Usage:
 *
 * ```tsx
 * import { Icon } from '~/components'
 *
 * // with "size"
 * <IconAdd size="sm" />
 *
 * // with "color"
 * <IconAdd color="green" />
 *
 * // with custom styles
 * <IconAdd style={{ width: 97, height: 20 }} />
 *
 * ```
 */
export * from './withIcon'

export * from './IconAdd'
export * from './IconAddMedium'
export * from './IconAppreciationMAX'
export * from './IconArchiveMedium'
export * from './IconAvatarLogo'
export * from './IconBackLarge'
export * from './IconBookmark'
export * from './IconBookmarkActive'
export * from './IconBookmarkMedium'
export * from './IconCameraMedium'
export * from './IconCheckActive'
export * from './IconCheckedMedium'
export * from './IconCheckInactive'
export * from './IconCheckMedium'
export * from './IconClear'
export * from './IconCloseLarge'
export * from './IconCollapse'
export * from './IconCollectionMedium'
export * from './IconComment'
export * from './IconDeleteDraftXS'
export * from './IconDotDivider'
export * from './IconDown'
export * from './IconDownVote'
export * from './IconDownVoteActive'
export * from './IconDraftMedium'
export * from './IconEdit'
export * from './IconEditXS'
export * from './IconEmptyAvatar'
export * from './IconEmptyWarning'
export * from './IconExpand'
export * from './IconExternal'
export * from './IconExternalLink'
export * from './IconHashTag'
export * from './IconHashTagMedium'
export * from './IconHeart'
export * from './IconHelpMedium'
export * from './IconHistoryMedium'
export * from './IconInfo'
export * from './IconIPFSMedium'
export * from './IconSuperLikeInfinite'
export * from './IconLeft'
export * from './IconLeftLarge'
export * from './IconLike'
export * from './IconLikeMedium'
export * from './IconLink'
export * from './IconLive'
export * from './IconLogo'
export * from './IconLogoGraph'
export * from './IconLogoutMedium'
export * from './IconMore'
export * from './IconMoreLarge'
export * from './IconMuteMedium'
export * from './IconNavFollow'
export * from './IconNavFollowActive'
export * from './IconNavHome'
export * from './IconNavHomeActive'
export * from './IconNavNotification'
export * from './IconNavNotificationActive'
export * from './IconNavSearch'
export * from './IconPen'
export * from './IconPinMedium'
export * from './IconProfileMedium'
export * from './IconReload'
export * from './IconRemoveMedium'
export * from './IconRight'
export * from './IconSearch'
export * from './IconSearchMedium'
export * from './IconSettingsMedium'
export * from './IconShare'
export * from './IconSort'
export * from './IconSpinner'
export * from './IconSuperLike'
export * from './IconUnlockMedium'
export * from './IconUnMuteMedium'
export * from './IconUnPinMedium'
export * from './IconUp'
export * from './IconUpVote'
export * from './IconUpVoteActive'
export * from './IconUser'
export * from './IconViewModeComfortable'
export * from './IconViewModeCompact'
export * from './IconViewModeDefault'
export * from './IconVolume'
export * from './IconWalletMedium'
export * from './IconWorld'
