/**
 * `<Icon>` component that render as `<svg>`
 *
 * Usage:
 *
 * ```tsx
 * import { Icon } from '~/components'
 *
 * // with "size"
 * <IconAdd size="sm" />
 *
 * // with "color"
 * <IconAdd color="green" />
 *
 * // with custom styles
 * <IconAdd style={{ width: 97, height: 20 }} />
 *
 * ```
 */
export * from './withIcon'

export * from './IconAdd16'
export * from './IconAdd24'
export * from './IconAnnouncementAll24'
export * from './IconAnnouncementCommunity24'
export * from './IconAnnouncementProduct24'
export * from './IconAnnouncementSeminar24'
export * from './IconArchive24'
export * from './IconArrowDown16'
export * from './IconArrowLeft16'
export * from './IconArrowRight16'
export * from './IconArrowRight8'
export * from './IconArrowUp16'
export * from './IconArticle16'
export * from './IconAvatarEmpty24'
export * from './IconAvatarLogo32'
export * from './IconAnalytics24'
export * from './IconBack32'
export * from './IconBookmark16'
export * from './IconBookmark24'
export * from './IconBookmarked16'
export * from './IconBroadcast24'
export * from './IconCamera16'
export * from './IconCamera24'
export * from './IconChecked'
export * from './IconCircle16'
export * from './IconCircle24'
export * from './IconClap16'
export * from './IconClap24'
export * from './IconClear16'
export * from './IconClose32'
export * from './IconCollapse16'
export * from './IconCollection24'
export * from './IconComment16'
export * from './IconCopy16'
export * from './IconDisallow16'
export * from './IconDonate24'
export * from './IconDot'
export * from './IconDownVote16'
export * from './IconDownVoted16'
export * from './IconDraft24'
export * from './IconDraftDelete12'
export * from './IconDraftEdit12'
export * from './IconEdit16'
export * from './IconEmail24'
export * from './IconEmptyWarning72'
export * from './IconExclaimHint'
export * from './IconExpand16'
export * from './IconExternalLink16'
export * from './IconFilter12'
export * from './IconFiatCurrency40'
export * from './IconHashTag16'
export * from './IconHashTag24'
export * from './IconHelp16'
export * from './IconHelp24'
export * from './IconHistory24'
export * from './IconImage24'
export * from './IconIncome24'
export * from './IconInfo16'
export * from './IconIPFS24'
export * from './IconIPFSGreen24'
export * from './IconISCN24'
export * from './IconLeft32'
export * from './IconLikeCoin40'
export * from './IconLink16'
export * from './IconLogbook1'
export * from './IconLogbook2'
export * from './IconLogbookBadge16'
export * from './IconLocked24'
export * from './IconLogo'
export * from './IconLogoGraph'
export * from './IconLogout24'
export * from './IconMetaMask24'
export * from './IconMore16'
export * from './IconMore32'
export * from './IconMute24'
export * from './IconNavFollowing24'
export * from './IconNavFollowingActive24'
export * from './IconNavHome24'
export * from './IconNavHomeActive24'
export * from './IconNavNotification24'
export * from './IconNavNotificationActive24'
export * from './IconNavSearch24'
export * from './IconNavSettings24'
export * from './IconPayout24'
export * from './IconPaywall16'
export * from './IconPen16'
export * from './IconPin24'
export * from './IconPrice12'
export * from './IconProfile24'
export * from './IconReadTime12'
export * from './IconRead16'
export * from './IconReadTimeTotal16'
export * from './IconReload12'
export * from './IconRemove24'
export * from './IconRss32'
export * from './IconSearch16'
export * from './IconSettings24'
export * from './IconSettings32'
export * from './IconShare16'
export * from './IconShare32'
export * from './IconSort16'
export * from './IconSpinner16'
export * from './IconSuperLike'
export * from './IconSupport'
export * from './IconTraveloggers16'
export * from './IconUnChecked'
export * from './IconUnfollow24'
export * from './IconUnlock24'
export * from './IconUnMute24'
export * from './IconUnPin24'
export * from './IconUpVote16'
export * from './IconUpVoted16'
export * from './IconUser16'
export * from './IconVolume32'
export * from './IconWallet24'
export * from './IconWalletConnect24'
export * from './IconWorld16'
export * from './IconTranslate16'
