/**
 * `<Icon>` component that render as `<svg>`
 *
 * Usage:
 *
 * ```tsx
 * import { Icon } from '~/components'
 *
 * // with "size"
 * <IconAdd size="sm" />
 *
 * // with "color"
 * <IconAdd color="green" />
 *
 * // with custom styles
 * <IconAdd style={{ width: 97, height: 20 }} />
 *
 * ```
 */
export * from './withIcon'

export * from './IconActionBookmark16'
export * from './IconActionBookmarked16'
export * from './IconActionDownVote16'
export * from './IconActionDownVoted16'
export * from './IconActionUpVote16'
export * from './IconActionUpVoted16'
export * from './IconAdd16'
export * from './IconAdd24'
export * from './IconArchive24'
export * from './IconArrowDown16'
export * from './IconArrowLeft16'
export * from './IconArrowRight16'
export * from './IconArrowUp16'
export * from './IconAvatarEmpty24'
export * from './IconAvatarLogo32'
export * from './IconBack32'
export * from './IconBookmark24'
export * from './IconCamera16'
export * from './IconCamera24'
export * from './IconCheck24'
export * from './IconChecked24'
export * from './IconCheckedActive16'
export * from './IconCheckedInactive16'
export * from './IconActionClap16'
export * from './IconClap24'
export * from './IconClear16'
export * from './IconClose32'
export * from './IconCollapse16'
export * from './IconCollection24'
export * from './IconActionComment16'
export * from './IconCopy16'
export * from './IconDonate24'
export * from './IconDot'
export * from './IconDraft24'
export * from './IconDraftDelete12'
export * from './IconDraftEdit12'
export * from './IconEdit16'
export * from './IconEmptyWarning72'
export * from './IconExpand16'
export * from './IconExternal16'
export * from './IconExternalLink16'
export * from './IconHashTag16'
export * from './IconHashTag24'
export * from './IconHelp24'
export * from './IconHistory24'
export * from './IconImage24'
export * from './IconInfo16'
export * from './IconIPFS24'
export * from './IconLeft32'
export * from './IconLogo'
export * from './IconLogoGraph'
export * from './IconLogout24'
export * from './IconMore16'
export * from './IconMore32'
export * from './IconMute24'
export * from './IconNavFollowing24'
export * from './IconNavFollowingActive24'
export * from './IconNavHome24'
export * from './IconNavHomeActive24'
export * from './IconNavNotification24'
export * from './IconNavNotificationActive24'
export * from './IconNavSearch24'
export * from './IconPen16'
export * from './IconPin24'
export * from './IconProfile24'
export * from './IconReload16'
export * from './IconRemove24'
export * from './IconSearch16'
export * from './IconSearch24'
export * from './IconSettings24'
export * from './IconActionShare16'
export * from './IconSort16'
export * from './IconSpinner16'
export * from './IconSuperLike'
export * from './IconUnlock24'
export * from './IconUnMute24'
export * from './IconUnPin24'
export * from './IconUser16'
export * from './IconViewModeComfortable24'
export * from './IconViewModeCompact24'
export * from './IconViewModeDefault24'
export * from './IconVolume16'
export * from './IconWallet24'
export * from './IconWorld16'
