export enum ERROR_CODES {
  // Common
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_USER_INPUT = 'BAD_USER_INPUT',

  ACTION_LIMIT_EXCEEDED = 'ACTION_LIMIT_EXCEEDED',
  ACTION_FAILED = 'ACTION_FAILED',

  UNABLE_TO_UPLOAD_FROM_URL = 'UNABLE_TO_UPLOAD_FROM_URL',

  NAME_INVALID = 'NAME_INVALID',
  NAME_EXISTS = 'NAME_EXISTS',
  DISPLAYNAME_INVALID = 'DISPLAYNAME_INVALID',

  // Auth
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  FORBIDDEN = 'FORBIDDEN',
  FORBIDDEN_BY_STATE = 'FORBIDDEN_BY_STATE',
  FORBIDDEN_BY_TARGET_STATE = 'FORBIDDEN_BY_TARGET_STATE',
  TOKEN_INVALID = 'TOKEN_INVALID',

  // Entity
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',
  ARTICLE_NOT_FOUND = 'ARTICLE_NOT_FOUND',
  ASSET_NOT_FOUND = 'ASSET_NOT_FOUND',
  DRAFT_NOT_FOUND = 'DRAFT_NOT_FOUND',
  TAG_NOT_FOUND = 'TAG_NOT_FOUND',
  NOTICE_NOT_FOUND = 'NOTICE_NOT_FOUND',
  CIRCLE_NOT_FOUND = 'CIRCLE_NOT_FOUND',

  // Article
  ARTICLE_REVISION_CONTENT_INVALID = 'ARTICLE_REVISION_CONTENT_INVALID',
  ARTICLE_REVISION_REACH_LIMIT = 'ARTICLE_REVISION_REACH_LIMIT',

  // User
  USER_EMAIL_INVALID = 'USER_EMAIL_INVALID',
  USER_EMAIL_EXISTS = 'USER_EMAIL_EXISTS',
  USER_EMAIL_NOT_FOUND = 'USER_EMAIL_NOT_FOUND',
  USER_PASSWORD_INVALID = 'USER_PASSWORD_INVALID',

  // Tag
  DUPLICATE_TAG = 'DUPLICATE_TAG',
  TOO_MANY_TAGS_FOR_ARTICLE = 'TOO_MANY_TAGS_FOR_ARTICLE',
  TAG_EDITORS_REACH_LIMIT = 'TAG_EDITORS_REACH_LIMIT',

  // Circle
  CIRCLE_CREATION_REACH_LIMIT = 'CIRCLE_CREATION_REACH_LIMIT',
  DUPLICATE_CIRCLE = 'DUPLICATE_CIRCLE',
  DUPLICATE_CIRCLE_SUBSCRIPTION = 'DUPLICATE_CIRCLE_SUBSCRIPTION',

  // Verification Code
  CODE_INVALID = 'CODE_INVALID',
  CODE_INACTIVE = 'CODE_INACTIVE',
  CODE_EXPIRED = 'CODE_EXPIRED',

  // LikeCoin
  LIKER_EMAIL_EXISTS = 'LIKER_EMAIL_EXISTS',
  LIKER_USER_ID_EXISTS = 'LIKER_USER_ID_EXISTS',

  // OAuth
  OAUTH_TOKEN_INVALID = 'OAUTH_TOKEN_INVALID',

  // Migration
  MIGRATION_REACH_LIMIT = 'MIGRATION_REACH_LIMIT',

  // Payment
  PAYMENT_AMOUNT_TOO_SMALL = 'PAYMENT_AMOUNT_TOO_SMALL',
  PAYMENT_AMOUNT_INVALID = 'PAYMENT_AMOUNT_INVALID',
  PAYMENT_BALANCE_INSUFFICIENT = 'PAYMENT_BALANCE_INSUFFICIENT',
  PAYMENT_PASSWORD_NOT_SET = 'PAYMENT_PASSWORD_NOT_SET',
  PAYMENT_REACH_MAXIMUM_LIMIT = 'PAYMENT_REACH_MAXIMUM_LIMIT',
}
