export const ANALYTICS = 'analytics'
export const ADD_TOAST = 'addToast'
export const REMOVE_TOAST = 'removeToast'
export const REFETCH_RESPONSES = 'refetchResponses'
export const REFETCH_TAG_DETAIL_ARTICLES = 'refetchTagDetailArticles'
