export const MINIMAL_CHARGE_AMOUNT = {
  HKD: 20,
}

export const MAXIMUM_CHARGE_AMOUNT = {
  HKD: 99999,
}

export enum PAYMENT_CURRENCY {
  HKD = 'HKD',
  LIKE = 'LIKE',
}

export const PLATFORM_FEE = {
  HKD: '3.4% + HKD 2.35',
}

/**
 * Error Messages
 *
 * @see {@url https://stripe.com/docs/error-codes}
 */
export const STRIPE_ERROR_MESSAGES = {
  zh_hant: {
    account_already_exists: '',
    account_country_invalid_address: '',
    account_invalid: '',
    account_number_invalid: '',
    alipay_upgrade_required: '',
    amount_too_large: '',
    amount_too_small: '',
    api_key_expired: '',
    authentication_required: '',
    balance_insufficient: '',
    bank_account_declined: '',
    bank_account_exists: '',
    bank_account_unusable: '',
    bank_account_unverified: '',
    bank_account_verification_failed: '',
    bitcoin_upgrade_required: '',
    card_decline_rate_limit_exceeded: '',
    card_declined: '',
    decline_code: '',
    charge_already_captured: '',
    charge_already_refunded: '',
    charge_disputed: '',
    charge_exceeds_source_limit: '',
    charge_expired_for_capture: '',
    charge_invalid_parameter: '',
    country_unsupported: '',
    coupon_expired: '',
    customer_max_payment_methods: '',
    customer_max_subscriptions: '',
    email_invalid: '',
    expired_card: '',
    idempotency_key_in_use: '',
    incorrect_address: '',
    incorrect_cvc: '',
    incorrect_number: '',
    incorrect_zip: '',
    instant_payouts_unsupported: '',
    invalid_card_type: '',
    invalid_characters: '',
    invalid_charge_amount: '',
    invalid_cvc: '',
    invalid_expiry_month: '',
    invalid_expiry_year: '',
    invalid_number: '',
    invalid_source_usage: '',
    invoice_no_customer_line_items: '',
    invoice_no_subscription_line_items: '',
    invoice_not_editable: '',
    invoice_payment_intent_requires_action: '',
    invoice_upcoming_none: '',
    livemode_mismatch: '',
    lock_timeout: '',
    missing: '',
    not_allowed_on_standard_account: '',
    order_creation_failed: '',
    order_required_settings: '',
    order_status_invalid: '',
    order_upstream_timeout: '',
    out_of_inventory: '',
    parameter_invalid_empty: '',
    parameter_invalid_integer: '',
    parameter_invalid_string_blank: '',
    parameter_invalid_string_empty: '',
    parameter_missing: '',
    parameter_unknown: '',
    parameters_exclusive: '',
    payment_intent_action_required: '',
    error_on_requires_action: '',
    payment_intent_authentication_failure: '',
    payment_intent_incompatible_payment_method: '',
    payment_intent_invalid_parameter: '',
    payment_intent_payment_attempt_failed: '',
    last_payment_error: '',
    payment_intent_unexpected_state: '',
    payment_method_unactivated: '',
    payment_method_unexpected_state: '',
    payouts_not_allowed: '',
    platform_api_key_expired: '',
    postal_code_invalid: '',
    processing_error: '',
    product_inactive: '',
    rate_limit: '',
    resource_already_exists: '',
    resource_missing: '',
    routing_number_invalid: '',
    secret_key_required: '',
    sepa_unsupported_account: '',
    setup_attempt_failed: '',
    last_setup_error: '',
    setup_intent_authentication_failure: '',
    setup_intent_invalid_parameter: '',
    setup_intent_unexpected_state: '',
    shipping_calculation_failed: '',
    sku_inactive: '',
    state_unsupported: '',
    legal_entity: '',
    tax_id_invalid: '',
    taxes_calculation_failed: '',
    testmode_charges_only: '',
    tls_version_unsupported: '',
    token_already_used: '',
    token_in_use: '',
    transfers_not_allowed: '',
    upstream_order_creation_failed: '',
    url_invalid: '',
  },
  zh_hans: {
    account_already_exists: '',
    account_country_invalid_address: '',
    account_invalid: '',
    account_number_invalid: '',
    alipay_upgrade_required: '',
    amount_too_large: '',
    amount_too_small: '',
    api_key_expired: '',
    authentication_required: '',
    balance_insufficient: '',
    bank_account_declined: '',
    bank_account_exists: '',
    bank_account_unusable: '',
    bank_account_unverified: '',
    bank_account_verification_failed: '',
    bitcoin_upgrade_required: '',
    card_decline_rate_limit_exceeded: '',
    card_declined: '',
    decline_code: '',
    charge_already_captured: '',
    charge_already_refunded: '',
    charge_disputed: '',
    charge_exceeds_source_limit: '',
    charge_expired_for_capture: '',
    charge_invalid_parameter: '',
    country_unsupported: '',
    coupon_expired: '',
    customer_max_payment_methods: '',
    customer_max_subscriptions: '',
    email_invalid: '',
    expired_card: '',
    idempotency_key_in_use: '',
    incorrect_address: '',
    incorrect_cvc: '',
    incorrect_number: '',
    incorrect_zip: '',
    instant_payouts_unsupported: '',
    invalid_card_type: '',
    invalid_characters: '',
    invalid_charge_amount: '',
    invalid_cvc: '',
    invalid_expiry_month: '',
    invalid_expiry_year: '',
    invalid_number: '',
    invalid_source_usage: '',
    invoice_no_customer_line_items: '',
    invoice_no_subscription_line_items: '',
    invoice_not_editable: '',
    invoice_payment_intent_requires_action: '',
    invoice_upcoming_none: '',
    livemode_mismatch: '',
    lock_timeout: '',
    missing: '',
    not_allowed_on_standard_account: '',
    order_creation_failed: '',
    order_required_settings: '',
    order_status_invalid: '',
    order_upstream_timeout: '',
    out_of_inventory: '',
    parameter_invalid_empty: '',
    parameter_invalid_integer: '',
    parameter_invalid_string_blank: '',
    parameter_invalid_string_empty: '',
    parameter_missing: '',
    parameter_unknown: '',
    parameters_exclusive: '',
    payment_intent_action_required: '',
    error_on_requires_action: '',
    payment_intent_authentication_failure: '',
    payment_intent_incompatible_payment_method: '',
    payment_intent_invalid_parameter: '',
    payment_intent_payment_attempt_failed: '',
    last_payment_error: '',
    payment_intent_unexpected_state: '',
    payment_method_unactivated: '',
    payment_method_unexpected_state: '',
    payouts_not_allowed: '',
    platform_api_key_expired: '',
    postal_code_invalid: '',
    processing_error: '',
    product_inactive: '',
    rate_limit: '',
    resource_already_exists: '',
    resource_missing: '',
    routing_number_invalid: '',
    secret_key_required: '',
    sepa_unsupported_account: '',
    setup_attempt_failed: '',
    last_setup_error: '',
    setup_intent_authentication_failure: '',
    setup_intent_invalid_parameter: '',
    setup_intent_unexpected_state: '',
    shipping_calculation_failed: '',
    sku_inactive: '',
    state_unsupported: '',
    legal_entity: '',
    tax_id_invalid: '',
    taxes_calculation_failed: '',
    testmode_charges_only: '',
    tls_version_unsupported: '',
    token_already_used: '',
    token_in_use: '',
    transfers_not_allowed: '',
    upstream_order_creation_failed: '',
    url_invalid: '',
  },
}
