export const STORAGE_KEY_PUSH = '__PUSH'

export const STORAGE_KEY_AGENT_HASH = '__AGENT_HASH'

export const STORAGE_KEY_BILLBOARD = '__BILLBOARD'

export const STORAGE_KEY_CIRCLE_BANNER = '__CIRCLE_BANNER'

export const STORAGE_KEY_SEARCH_HISTORY = '__SEARCH_HISTORY'

export const REFERRAL_QUERY_REFERRAL_KEY = 'referral'
export const REFERRAL_STORAGE_REFERRAL_CODE = '__REFERRAL_CODE'

export const HAS_SHOW_MOMENT_BANNER = '__HAS_SHOW_MOMENT_BANNER'

export const NEW_POST_COMMENT_MUTATION_RESULT =
  '__NEW_POST_COMMENT_MUTATION_RESULT'

export const STORAGE_ACCESS_TOKEN_EXPIRES_AT = '__ACCESS_TOKEN_EXPIRES_AT'
