export const STORAGE_KEY_PUSH = '__PUSH'

export const STORAGE_KEY_AGENT_HASH = '__AGENT_HASH'

export const STORAGE_KEY_ONBOARDING_TASKS = '__ONBOARDING_TASKS'

export const STORAGE_KEY_CIRCLE_BANNER = '__CIRCLE_BANNER'

export const STORAGE_KEY_ANNOUNCEMENT = '__ANNOUNCEMENT'
