export enum TEST_ID {
  // components
  ARTICLE_DIGEST_CARD = 'ARTICLE_DIGEST_CARD',
  ARTICLE_DIGEST_FEED = 'ARTICLE_DIGEST_FEED',
  ARTICLE_DIGEST_SIDEBAR = 'ARTICLE_DIGEST_SIDEBAR',
  ARTICLE_DIGEST_TITLE = 'ARTICLE_DIGEST_TITLE',
  USER_DIGEST_MINI = 'USER_DIGEST_MINI',
  USER_DIGEST_PLAIN = 'USER_DIGEST_PLAIN',
  USER_DIGEST_RICH = 'USER_DIGEST_RICH',
  USER_DIGEST_VERBOSE = 'USER_DIGEST_VERBOSE',
  TAG_DIGEST_FEED = 'TAG_DIGEST_FEED',
  TAG_DIGEST_RICH = 'TAG_DIGEST_RICH',
  TAG_DIGEST_SIDEBAR = 'TAG_DIGEST_SIDEBAR',
}
