export type TextId = keyof typeof TEXT.zh_hant

export const TEXT = {
  zh_hant: {
    about: '關於我們',
    accountArchived: '已註銷用戶',
    accountBanned: '已禁言用戶',
    accountFrozen: '已凍結用戶',
    accountSetting: '帳戶設定',
    ACTION_FAILED: '操作失敗，請稍候重試',
    ACTION_LIMIT_EXCEEDED: '操作過於頻繁，請稍候重試',
    addArticleTag: '添加作品',
    addedArticleTag: '作品已添加標籤',
    agree: '同意',
    agreeAndContinue: '同意並繼續',
    allAuthors: '全部作者',
    allTags: '全部標籤',
    allTopics: '熱議廣場',
    allIcymi: '不要錯過',
    appreciationsReceived: '讚賞我的',
    appreciationsSent: '我讚賞的',
    ARTICLE_NOT_FOUND: '作品不存在',
    article: '作品',
    archived: '隱藏',
    articleArchived: '該作品已從站內隱藏',
    articleBanned: '作品因違反社區約章被隱藏',
    articleFingerprint: '作品指紋',
    ASSET_NOT_FOUND: '資源不存在',
    authorRecommend: '作者精選',
    back: '返回',
    backToDiscover: '返回發現',
    BAD_USER_INPUT: '出錯了，請檢查你輸入的內容',
    block: '封鎖',
    blockedSetting: '封鎖用戶',
    blockUser: '封鎖用戶',
    bookmark: '收藏',
    cancel: '取消',
    change: '修改',
    changeEmail: '修改電子信箱',
    changePassword: '修改密碼',
    changeUserName: '修改 Matters ID',
    close: '關閉',
    CODE_EXPIRED: '驗證碼已過期',
    CODE_INVALID: '驗證碼不正確',
    collapseComment: '闔上評論',
    collectedOnly: '只看衍生作品',
    COMMENT_NOT_FOUND: '評論不存在',
    comment: '評論',
    commentBlocked: '你封鎖了該用戶',
    commentCollapsed: '評論被創作者闔上',
    commentDeleted: '評論被原作者刪除',
    putComment: '發表評論',
    commentPlaceholder: '發表你的評論…',
    confirm: '確認',
    confirmPush: '確認開啟',
    continue: '繼續',
    copy: '複製',
    create: '創建',
    createTag: '新增標籤',
    delete: '刪除',
    deleteArticleTag: '作品已移除標籤',
    deleteComment: '刪除評論',
    deleteDraft: '刪除草稿',
    disagree: '我不同意',
    discover: '發現',
    displayName: '姓名',
    done: '完成',
    downloadApp: '下載應用',
    DRAFT_NOT_FOUND: '草稿不存在',
    draft: '草稿',
    DUPLICATE_TAG: '標籤名稱已被使用',
    edit: '編輯',
    editComment: '編輯評論',
    editTag: '編輯標籤',
    editUserProfile: '編輯資料',
    email: '電子信箱',
    emptySearchResults: '不好意思，什麼都沒搜到',
    enterDisplayName: '請輸入姓名',
    enterEmail: '請輸入電子信箱',
    enterNewEmail: '請輸入新電子信箱',
    enterPassword: '請輸入密碼',
    enterPasswordAgain: '請再次輸入密碼',
    enterRegisteredEmail: '請輸入你的註冊電子信箱',
    enterUserDescription: '請輸入個人簡介',
    enterUserName: '請輸入 Matters ID',
    enterUserNameAgign: '請再次輸入 Matters ID',
    enterVerificationCode: '請輸入驗證碼',
    ENTITY_NOT_FOUND: '實體不存在',
    expand: '展開',
    extend: '關聯',
    extendArticle: '關聯作品',
    failureChange: '修改失敗，請稍候重試',
    failureCopy: '複製失敗',
    failureLogout: '登出失敗，請重試',
    failurePublish: '發佈失敗',
    failureUploadImage: '圖片上傳失敗',
    faq: '新手指南',
    featured: '精選',
    featuredComments: '社區精選',
    follow: '追蹤',
    followAuthor: '追蹤創作者',
    followed: '已追蹤',
    follower: '追蹤者',
    following: '追蹤中',
    followingMe: '追蹤我的',
    followingYou: '追蹤了你',
    FORBIDDEN: '你尚無權限進行該操作',
    forgetPassword: '忘記密碼',
    guide: '社區約章',
    helpCenter: '幫助中心',
    hide: '站內隱藏',
    hintDisplayName: '2-20 個字元，僅支持中英文或數字',
    hintPassword: '至少 8 個字元，支持英文大小寫字母、數字和特殊符號',
    hintTerm: '我們的用戶協議和隱私政策發生了更改，請閱讀並同意後繼續使用。',
    hintUserDescription: '建議 50 字以內，最長 200 字',
    hintUserName: '4-15 個字元，僅支持英文、數字及下劃線',
    history: '足跡',
    hottestArticles: '熱門作品',
    INTERNAL_SERVER_ERROR: '伺服器錯誤，請稍候重試',
    invalidEmail: '電子信箱格式有誤',
    invalidUserName: 'Matters ID 不一致',
    IPFSEntrance: '分佈式入口',
    joinCivicLiker: '成為讚賞公民，直接贊助創作者',
    latest: '最新',
    latestArticles: '最新作品',
    latestResponses: '最新回應',
    LIKER_EMAIL_EXISTS: 'Liker ID 電子信箱已被其他人使用',
    LIKER_NOT_FOUND: 'Liker ID 不存在',
    LIKER_USER_ID_EXISTS: 'Liker ID 已被其他人使用',
    login: '登入',
    loginPassword: '登入密碼',
    logout: '登出',
    migration: '搬家到 Matters',
    migrationSideBar: '一鍵搬家',
    MIGRATION_REACH_LIMIT: '導入作品累計超過 1 MB',
    moreActions: '更多操作',
    mutualFollowing: '互相追蹤',
    myBookmarks: '我的收藏',
    myDrafts: '我的草稿',
    myAppreciations: '我的讚賞',
    myFollowees: '我追蹤的',
    myProfile: '個人主頁',
    NETWORK_ERROR: '網路錯誤，請用力刷新',
    newPassword: '新密碼',
    nextStep: '下一步',
    NOT_ENOUGH_MAT: '沒有足夠的 MAT 以讚賞',
    NOTICE_NOT_FOUND: '通知不存在',
    notification: '通知',
    notificationSetting: '通知設定',
    password: '密碼',
    passwordHint: '至少 8 個字元，支持英文大小寫字母、數字和特殊符號',
    passwordNotMatch: '密碼不一致',
    pin: '喜歡回應',
    previousStep: '上一步',
    publishing: '正在發佈，馬上就好',
    publish: '發佈',
    pushDescription: '別錯過精彩討論和最新消息，快點開啓推送吧！',
    QUERY_FIELD_NOT_FOUND: '要查詢的數據不存在',
    RATE_LIMIT_EXCEEDED: '操作過於頻繁，請稍候重試',
    readHistory: '瀏覽記錄',
    refuse: '拒絕',
    register: '註冊',
    reply: '回覆',
    replyComment: '回覆評論',
    report: '檢舉',
    required: '必填欄位',
    resend: '重新發送',
    resetPassword: '重置密碼',
    response: '回應',
    retry: '重試',
    revoke: '撤銷',
    save: '儲存',
    search: '搜尋',
    searchHistory: '搜尋歷史',
    searchTag: '搜尋你想創建的標籤…',
    sendVerificationCode: '發送驗證碼',
    frequentSearch: '熱門搜尋',
    setting: '設定',
    setup: '設置',
    setupLikeCoin: '設置 Liker ID',
    share: '分享',
    shuffle: '換一批',
    stickyArticle: '置頂作品',
    successBlock: '已封鎖。該用戶無法評論你的作品，他的評論對你闔上。',
    successChangeEmail: '電子信箱修改成功',
    successChangePassword: '密碼修改成功，請不要告訴別人',
    successChangeUserName: 'Matters ID 修改成功',
    successCollapseComment: '此評論已被你成功闔上，其他用戶需打開才可查看。',
    successCopy: '複製成功',
    successEditUserProfile: '資料已保存',
    successLogin: '登入成功',
    successLogout: '登出成功',
    successRegister: '註冊成功',
    successResetPassword: '密碼重置成功',
    successUnblock: '已取消封鎖。該用戶現在可以評論你的作品。',
    successUploadImage: '圖片上傳成功',
    TAG_NOT_FOUND: '標籤不存在',
    tag: '標籤',
    tagCreated: '標籤已創建',
    tagDescription: '標籤描述',
    tagDescriptionPlaceholder: '輸入一段標籤描述…',
    tagEdited: '標籤已更新',
    tagName: '標籤名稱',
    term: '用戶協議',
    termAndPrivacy: '用戶協議與隱私政策',
    termHint: '我們的用戶協議和隱私政策發生了更改，請閱讀並同意後繼續使用。',
    TOKEN_INVALID: '登入信息已失效，請重新登入',
    topic: '話題',
    oauthAuthorize: '應用授權',
    openCommunity: '開放社區',
    uiSetting: '介面設定',
    UNABLE_TO_UPLOAD_FROM_URL:
      '檔案上傳失敗，請確認檔案連結是否有效，或手動下載後再上傳',
    UNAUTHENTICATED: '請先登入再進行操作',
    unblockUser: '取消封鎖',
    uncollapseComment: '取消闔上',
    understood: '我知道了',
    unfollow: '取消追蹤',
    UNKNOWN_ERROR: '不知道哪裏出錯了，過幾分鐘看看',
    unpin: '取消精選',
    unstickyArticle: '取消置頂',
    untitle: '未命名',
    useNewPassword: '請使用新的密碼重新登入',
    USER_DISPLAYNAME_INVALID: '姓名不正確',
    USER_EMAIL_EXISTS: '電子信箱被其他人用了，換一個吧',
    USER_EMAIL_INVALID: '電子信箱不正確',
    USER_EMAIL_NOT_FOUND: '帳號不正確',
    USER_NOT_FOUND: '用戶不存在',
    USER_PASSWORD_INVALID: '密碼不正確',
    USER_USERNAME_EXISTS: '該 Matters ID 已被其他使用者使用',
    USER_USERNAME_INVALID: 'Matters ID 不正確',
    user: '用戶',
    userDescription: '個人簡介',
    verificationCode: '驗證碼',
    viewAll: '查看全部',
    viewAppreciators: '查看赞赏',
    waitingForPublish: '正在等待發佈，星際通道有點擁擠',
    walletSetting: '錢包設定',
    write: '創作',
    yourEmail: '你的電子信箱'
  },
  zh_hans: {
    about: '关于我们',
    accountArchived: '已注销用户',
    accountBanned: '已禁言用户',
    accountFrozen: '已冻结用户',
    accountSetting: '账户设定',
    ACTION_FAILED: '操作失败，请稍候重试',
    ACTION_LIMIT_EXCEEDED: '操作过于频繁，请稍候重试',
    addArticleTag: '添加作品',
    addedArticleTag: '作品已添加标签',
    agree: '同意',
    agreeAndContinue: '同意并继续',
    allAuthors: '全部作者',
    allTags: '全部标签',
    allTopics: '热议广场',
    allIcymi: '不要错过',
    appreciationsReceived: '赞赏我的',
    appreciationsSent: '我赞赏的',
    ARTICLE_NOT_FOUND: '作品不存在',
    article: '作品',
    archived: '隐藏',
    articleArchived: '该作品已从站内隐藏',
    articleBanned: '作品因违反社区约章被隐藏',
    articleFingerprint: '作品指纹',
    ASSET_NOT_FOUND: '资源不存在',
    authorRecommend: '作者精选',
    back: '返回',
    backToDiscover: '返回发现',
    BAD_USER_INPUT: '出错了，请检查你输入的内容',
    block: '屏蔽',
    blockedSetting: '屏蔽用户',
    blockUser: '屏蔽用户',
    bookmark: '收藏',
    cancel: '取消',
    change: '修改',
    changeEmail: '修改邮箱',
    changePassword: '修改密码',
    changeUserName: '修改 Matters ID',
    close: '关闭',
    CODE_EXPIRED: '验证码已过期',
    CODE_INVALID: '验证码不正确',
    collapseComment: '折叠评论',
    collectedOnly: '只看衍生作品',
    COMMENT_NOT_FOUND: '评论不存在',
    comment: '评论',
    commentBlocked: '你屏蔽了该用户',
    commentCollapsed: '评论被创作者折叠',
    commentDeleted: '评论被原作者删除',
    putComment: '发表评论',
    commentPlaceholder: '发表你的评论…',
    confirm: '确认',
    confirmPush: '确认开启',
    continue: '继续',
    copy: '复制',
    create: '创建',
    createTag: '新建标签',
    delete: '删除',
    deleteArticleTag: '作品已移除标签',
    deleteComment: '删除评论',
    deleteDraft: '刪除草稿',
    disagree: '我不同意',
    discover: '发现',
    displayName: '姓名',
    done: '完成',
    downloadApp: '下载应用',
    DRAFT_NOT_FOUND: '草稿不存在',
    draft: '草稿',
    DUPLICATE_TAG: '标签名称已被使用',
    edit: '编辑',
    editComment: '编辑评论',
    editTag: '编辑标签',
    editUserProfile: '编辑资料',
    email: '邮箱',
    emptySearchResults: '不好意思，什么都没搜到',
    enterDisplayName: '请输入姓名',
    enterEmail: '请输入邮箱',
    enterNewEmail: '请输入新邮箱',
    enterPassword: '请输入密码',
    enterPasswordAgain: '请再次输入密码',
    enterRegisteredEmail: '请输入你的注册邮箱',
    enterUserDescription: '请输入个人简介',
    enterUserName: '请输入新 Matters ID',
    enterUserNameAgign: '请再次输入新 Matters ID',
    enterVerificationCode: '请输入验证码',
    ENTITY_NOT_FOUND: '实体不存在',
    expand: '展开',
    extend: '关联',
    extendArticle: '关联作品',
    failureChange: '修改失败，请稍候重试',
    failureCopy: '复制失败',
    failureLogout: '登出失败，再来一次',
    failurePublish: '发布失败',
    failureUploadImage: '图片上传失败',
    faq: '新手指南',
    featured: '精选',
    featuredComments: '社区精选',
    follow: '追踪',
    followAuthor: '追踪创作者',
    followed: '已追踪',
    follower: '追踪者',
    following: '追踪中',
    followingMe: '追踪我的',
    followingYou: '追踪了你',
    FORBIDDEN: '你尚无权限进行该操作',
    forgetPassword: '忘记密码',
    guide: '社区约章',
    hide: '站内隐藏',
    helpCenter: '帮助中心',
    hintDisplayName: '2-20 位，仅支持中英文或数字',
    hintPassword: '至少 8 位，支持英文大小写字母、数字和特殊符号',
    hintTerm: '我们的用户协议和隐私政策发生了更改，请阅读并同意后继续使用。',
    hintUserDescription: '建议 50 字以内，最长 200 字',
    hintUserName: '4-15 位，仅支持英文、数字及下划线',
    history: '足迹',
    hottestArticles: '热门作品',
    INTERNAL_SERVER_ERROR: '服务器错误，请稍候重试',
    invalidEmail: '邮箱格式有误',
    invalidUserName: 'Matters ID 不一致',
    IPFSEntrance: '分布式入口',
    joinCivicLiker: '成为赞赏公民，直接赞助创作者',
    latest: '最新',
    latestArticles: '最新作品',
    latestResponses: '最新回应',
    LIKER_EMAIL_EXISTS: 'Liker ID 邮箱已被其他人使用',
    LIKER_NOT_FOUND: 'Liker ID 不存在',
    LIKER_USER_ID_EXISTS: 'Liker ID 已被其他人使用',
    login: '登录',
    loginPassword: '登录密码',
    logout: '登出',
    migration: '搬家到 Matters',
    migrationSideBar: '一鍵搬家',
    MIGRATION_REACH_LIMIT: '导入作品累計超过 1 MB',
    moreActions: '更多操作',
    mutualFollowing: '互相追踪',
    myBookmarks: '我的收藏',
    myAppreciations: '我的赞赏',
    myDrafts: '我的草稿',
    myFollowees: '我追踪的',
    myProfile: '个人主页',
    NETWORK_ERROR: '网络不给力，请用力刷新',
    newPassword: '新密码',
    nextStep: '下一步',
    NOT_ENOUGH_MAT: '没有足够的 MAT 以赞赏',
    NOTICE_NOT_FOUND: '通知不存在',
    notification: '通知',
    notificationSetting: '通知设定',
    password: '密码',
    passwordHint: '至少 8 位，支持英文大小写字母、数字和特殊符号',
    passwordNotMatch: '密码不一致',
    pin: '喜欢回应',
    previousStep: '上一步',
    publishing: '正在发布，马上就好',
    publish: '发布',
    pushDescription: '别错过精彩讨论和最新消息，快点开启推送吧！',
    QUERY_FIELD_NOT_FOUND: '要查询的数据不存在',
    RATE_LIMIT_EXCEEDED: '操作过于频繁，请稍候重试',
    readHistory: '浏览记录',
    refuse: '拒绝',
    register: '注册',
    reply: '回复',
    replyComment: '回复评论',
    report: '检举',
    required: '必填栏位',
    resend: '重新发送',
    resetPassword: '重置密码',
    response: '回应',
    retry: '重试',
    revoke: '撤销',
    save: '保存',
    search: '搜索',
    searchHistory: '搜索历史',
    searchTag: '搜索你想创建的标签…',
    frequentSearch: '热门搜索',
    sendVerificationCode: '发送验证码',
    setting: '设定',
    setup: '设置',
    setupLikeCoin: '设置 Liker ID',
    share: '分享',
    shuffle: '换一批',
    stickyArticle: '置顶作品',
    successBlock: '已屏蔽。该用户无法评论你的作品，他的评论对你折叠。',
    successChangeEmail: '邮箱修改成功',
    successChangePassword: '密码修改成功，请不要告诉别人',
    successChangeUserName: 'Matters ID 修改成功',
    successCollapseComment: '此评论已被你成功折叠，其他用户需展开才可查看。',
    successCopy: '复制成功',
    successEditUserProfile: '资料已保存',
    successLogin: '上站成功',
    successLogout: '登出成功',
    successRegister: '注册成功',
    successResetPassword: '密码重置成功',
    successUnblock: '已取消屏蔽。该用户现在可以评论你的作品。',
    successUpdateUserProfile: '',
    successUploadImage: '图片上传成功',
    TAG_NOT_FOUND: '标签不存在',
    tag: '标签',
    tagCreated: '标签已创建',
    tagDescription: '标签描述',
    tagDescriptionPlaceholder: '输入一段话题描述…',
    tagEdited: '标签已更新',
    tagName: '标签名称',
    term: '用户协议',
    termAndPrivacy: '用户协议与隐私政策',
    termHint: '我们的用户协议和隐私政策发生了更改，请阅读并同意后继续使用。',
    TOKEN_INVALID: '登录信息已失效，请重新登录',
    topic: '话题',
    oauthAuthorize: '应用授权',
    openCommunity: '开放社区',
    uiSetting: '界面设定',
    UNABLE_TO_UPLOAD_FROM_URL:
      '文件上传失败，请确认文件链接是否有效，或手动下载后再上传',
    UNAUTHENTICATED: '请先登录再进行操作',
    unblockSuccess: '已取消屏蔽。该用户现在可以评论你的作品。',
    unblockUser: '取消屏蔽',
    uncollapseComment: '取消折叠',
    understood: '我知道了',
    unfollow: '取消追踪',
    UNKNOWN_ERROR: '不知道哪里出错了，过几分钟看看',
    unpin: '取消精选',
    unstickyArticle: '取消置顶',
    untitle: '未命名',
    useNewPassword: '请使用新的密码重新登录',
    USER_DISPLAYNAME_INVALID: '姓名不正确',
    USER_EMAIL_EXISTS: '邮箱被其他人用了，换一个吧',
    USER_EMAIL_INVALID: '邮箱不正确',
    USER_EMAIL_NOT_FOUND: '帐号不正确',
    USER_NOT_FOUND: '用户不存在',
    USER_PASSWORD_INVALID: '密码不正确',
    USER_USERNAME_EXISTS: '该 Matters ID 已被其他用户使用',
    USER_USERNAME_INVALID: 'Matters ID 不正确',
    user: '用户',
    userDescription: '个人简介',
    verificationCode: '验证码',
    viewAll: '查看全部',
    viewAppreciators: '查看讚賞',
    waitingForPublish: '正在等待发布，星际通道有点拥挤',
    walletSetting: '钱包设定',
    write: '创作',
    yourEmail: '你的邮箱'
  }
}
